from django.urls import path

from . import views

urlpatterns = [
    path("login", views.login, name="login"),
    path("register", views.register, name="register"),
    path("logout", views.logout, name="logout"),
    path("password-recovery", views.PasswordRecoverView.as_view(), name="password_reset"),
    path("password-recovery-confirm/<uidb64>/<token>", views.PasswordRecoveryConfirmView.as_view(),
         name="password_reset_confirm"),
    path("password-recovery-done", views.PasswordRecoveryDoneView.as_view(), name="password_reset_done"),
    path("password-recovery-complete", views.PasswordRecoveryCompleteView.as_view(), name="password_reset_complete"),
    path("profile", views.user_profile, name="user_profile"),
    path("change-account-data", views.ChangeAccountDataView.as_view(), name="change_account_data"),
    path("landing-page-editor", views.LandingPageEditorView.as_view(), name="landing_page_editor"),
    path("gallery-editor", views.GalleryEditorView.as_view(), name="gallery_editor"),
    path("gallery-editor-image-filter", views.gallery_editor_image_filter, name="gallery_editor_image_filter"),
    path("gallery-add/<_type>", views.GalleryAddView.as_view(), name="gallery_add"),
    path("gallery-delete/<_type>/<int:pk>", views.GalleryDeleteView.as_view(),
         name="gallery_delete"),
    path("user-manager", views.UserManagerView.as_view(), name="user_manager"),
    path("blocked-user/<b_status>/<int:pk>", views.BlockUserView.as_view(), name="blocked_user"),
    path("change-user-password", views.ChangeUserPasswordView.as_view(), name="change_user_password"),
    path("notifications", views.NotificationsView.as_view(), name="notifications"),
    path("comms-history", views.CommsHistoryView.as_view(), name="comms_history"),
    path("comms-in-progress", views.CommsInProgressView.as_view(), name="comms_in_progress"),
    path("cancel-comm/<uuid:uuid>", views.CancelCommissionView.as_view(), name="cancel_comm"),
    path("accept-comm/<uuid:uuid>", views.AcceptCommissionView.as_view(), name="accept_comm"),
    path("comm-next-stage/<uuid:uuid>", views.CommissionNextStageView.as_view(), name="comm_next_stage"),
    path("comm-detail/<uuid:pk>", views.CommsInProgressDetailsView.as_view(), name="comm_detail"),
    path("chat/<uuid:uuid>", views.CommChat.as_view(), name="comm_chat"),
    path("payment/<uuid:uuid>/currency-choice", views.payment_currency_choice, name="currency_choice"),
    path("payment_brl/<uuid:uuid>/", views.Payment_BRL_View.as_view(), name="payment_brl"),
    path("payment_usd/<uuid:uuid>/", views.Payment_USD_View.as_view(), name="payment_usd"),
]
