# Generated by Django 6.0.5 on 2026-06-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='level',
            field=models.CharField(default='MESSAGE', max_length=24),
            preserve_default=False,
        ),
    ]
