# Generated by Django 6.0.5 on 2026-06-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(default='MESSAGE', max_length=24),
        ),
    ]
