# Generated by Django 6.0.5 on 2026-05-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=24)),
                ('artist_icon', models.ImageField(upload_to='landing')),
                ('occupation', models.CharField(max_length=40)),
                ('instagram', models.CharField(max_length=24)),
                ('twitter', models.CharField(max_length=24)),
                ('youtube', models.CharField(max_length=24)),
                ('tiktok', models.CharField(max_length=24)),
                ('slots', models.IntegerField()),
                ('comms_status', models.BooleanField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
