# Generated by Django 6.0.5 on 2026-05-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_gallerytag_galleryimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImages',
            new_name='GalleryImage',
        ),
    ]
