# Generated by Django 6.0.5 on 2026-08-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_rename_galleryimages_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='artist_icon',
            field=models.ImageField(null=True, upload_to='landing'),
        ),
    ]
