# Generated by Django 6.0.5 on 2026-07-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messageimage_remove_message_is_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
