# Generated by Django 6.0.5 on 2026-05-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blocked_reason',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_blocked',
        ),
    ]
