# Generated by Django 6.0.5 on 2026-06-19 00:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('019edd52-130d-7008-99e6-484e5d0432b6'), editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('waiting_confirmation', 'aguardando confirmação'), ('waiting_deposit_payment', 'aguardando pagamento da garantia'), ('sketch', 'esboço'), ('lineart', 'lineart'), ('flat_colour', 'cor flat'), ('render', 'render'), ('waiting_full_payment', 'aguardando pagamento total'), ('finished', 'concluído'), ('canceled', 'cancelado')], max_length=24)),
                ('category', models.CharField(choices=[('character', 'personagem'), ('landscape', 'cenário'), ('objects', 'objetos')], default='character', max_length=24)),
                ('final_stage', models.CharField(choices=[('sketch', 'esboço'), ('lineart', 'lineart'), ('flat_colour', 'cor flat'), ('render', 'render')], default='render', max_length=24)),
                ('character_type', models.CharField(choices=[('human', 'humano'), ('furry', 'furry'), ('chibi', 'chibi'), ('creature', 'criatura')], default='human', max_length=24, null=True)),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('complexity', models.CharField(choices=[('simple', 'simples'), ('complex', 'complexo')], default='simple', max_length=12, null=True)),
                ('art_type', models.CharField(choices=[('illustration', 'ilustração'), ('scene', 'cena'), ('sheet', 'sheet')], default='illustration', max_length=24, null=True)),
                ('clothing', models.CharField(choices=[('mannequin', 'manequim'), ('simple', 'simples'), ('complex', 'complexo'), ('accessories', 'acessórios')], default='mannequin', max_length=24, null=True)),
                ('body_type', models.CharField(choices=[('bust', 'busto'), ('waist', 'quadril'), ('full', 'full')], default='bust', max_length=12, null=True)),
                ('background', models.CharField(choices=[('preset', 'preset'), ('simple', 'simples'), ('complex', 'complexo')], default='preset', max_length=12, null=True)),
                ('aspect_ratio', models.CharField(choices=[('1:1', '1:1'), ('3:2', '3:2'), ('16:9', '16:9'), ('1.85:1', '1.85:1')], default='1:1', max_length=12)),
                ('fx', models.BooleanField(choices=[(True, 'sim'), (False, 'não')], default=False)),
                ('description', models.TextField(max_length=3000)),
                ('commercial', models.BooleanField(default=False)),
                ('share_permission', models.BooleanField(default=False)),
                ('contact_social', models.CharField(max_length=30)),
                ('contact_username', models.CharField(max_length=60)),
                ('price_brl', models.FloatField()),
                ('price_usd', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commission/reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commissions.commission')),
            ],
        ),
    ]
