# Generated by Django 6.0.5 on 2026-06-19 12:07

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='art_type',
            field=models.CharField(blank=True, choices=[('illustration', 'ilustração'), ('scene', 'cena'), ('sheet', 'sheet')], default='illustration', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='background',
            field=models.CharField(blank=True, choices=[('preset', 'preset'), ('simple', 'simples'), ('complex', 'complexo')], default='preset', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='body_type',
            field=models.CharField(blank=True, choices=[('bust', 'busto'), ('waist', 'quadril'), ('full', 'full')], default='bust', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='character_type',
            field=models.CharField(blank=True, choices=[('human', 'humano'), ('furry', 'furry'), ('chibi', 'chibi'), ('creature', 'criatura')], default='human', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='clothing',
            field=models.CharField(blank=True, choices=[('mannequin', 'manequim'), ('simple', 'simples'), ('complex', 'complexo'), ('accessories', 'acessórios')], default='mannequin', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='complexity',
            field=models.CharField(blank=True, choices=[('simple', 'simples'), ('complex', 'complexo')], default='simple', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='commission',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('019edfc7-9130-74d0-9ae4-5e724333a87d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
