# Generated by Django 6.0.5 on 2026-06-20 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_commission_art_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='aspect_ratio',
            field=models.CharField(choices=[('1:1', '1:1'), ('3:2', '3:2'), ('16:9', '16:9'), ('1.85:1', '1.85:1')], default='3:2', max_length=12),
        ),
        migrations.AlterField(
            model_name='commission',
            name='body_type',
            field=models.CharField(blank=True, choices=[('bust', 'busto'), ('waist', 'quadril'), ('full', 'full')], default='full', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='clothing',
            field=models.CharField(blank=True, choices=[('mannequin', 'manequim'), ('simple', 'simples'), ('complex', 'complexo'), ('accessories', 'acessórios')], default='simple', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('019ee45e-c3a1-7503-bda3-4ee9db0d3ab5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
