# Generated by Django 6.0.5 on 2026-06-20 23:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_commission_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='background',
            field=models.CharField(blank=True, choices=[('simple', 'simples'), ('complex', 'complexo'), ('preset', 'preset')], default='simple', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='category',
            field=models.CharField(choices=[('character', 'personagem'), ('landscape', 'cenário'), ('object', 'objetos')], default='character', max_length=24),
        ),
        migrations.AlterField(
            model_name='commission',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('019ee76a-bee4-70b9-982c-6722850f3a6c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
