# Generated by Django 6.0.5 on 2026-06-21 09:54

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_alter_commission_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='commission',
            name='final_stage',
            field=models.CharField(choices=[('lineart', 'lineart'), ('flat_colour', 'cor flat'), ('render', 'render')], default='render', max_length=24),
        ),
        migrations.AlterField(
            model_name='commission',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('019ee99a-c9ce-76ed-a9c9-d05f1feeb457'), editable=False, primary_key=True, serialize=False),
        ),
    ]
