# Generated by Django 6.0.5 on 2026-06-24 19:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_alter_commission_count_alter_commission_final_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceimage',
            name='id',
        ),
        migrations.AddField(
            model_name='referenceimage',
            name='is_temp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='referenceimage',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('019efb31-87be-75bc-8acb-67d478f3bb94'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commission',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('019efb31-87be-75bc-8acb-67d3355a8e5a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
