# Generated by Django 6.0.5 on 2026-06-24 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_remove_referenceimage_id_referenceimage_is_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('019efb3e-1be2-764c-a58c-e55482786775'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referenceimage',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.commission'),
        ),
        migrations.AlterField(
            model_name='referenceimage',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('019efb3e-1be2-764c-a58c-e5554092bf5f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
