# Generated by Django 6.0.5 on 2026-06-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0008_alter_commission_uuid_alter_referenceimage_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='character_type',
            field=models.CharField(blank=True, choices=[('human', 'humano'), ('furry', 'furry'), ('chibi', 'chibi'), ('simple_creature', 'criatura simples'), ('complex_creature', 'criatura complexa')], default='human', max_length=24, null=True),
        ),
    ]
