# Generated by Django 6.0.5 on 2026-06-30 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0010_alter_commission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceimage',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='commissions.commission'),
        ),
        migrations.CreateModel(
            name='FinalImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='commission/reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_image', to='commissions.commission')),
            ],
        ),
    ]
