# Generated by Django 6.0.5 on 2026-06-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0011_alter_referenceimage_commission_finalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalimage',
            name='image',
            field=models.ImageField(upload_to='commission/final'),
        ),
    ]
