# Generated by Django 6.0.5 on 2026-06-30 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0012_alter_finalimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalimage',
            name='commission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_image', to='commissions.commission'),
        ),
    ]
