# Generated by Django 6.0.5 on 2026-07-11 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0013_alter_finalimage_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='commission/progress')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_image', to='commissions.commission')),
            ],
        ),
    ]
