# Generated by Django 6.0.5 on 2026-07-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0014_progressimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressimage',
            name='stage',
            field=models.CharField(choices=[('sketch', 'esboço'), ('lineart', 'lineart'), ('flat_colour', 'cor flat'), ('render', 'render')], default='sketch', max_length=24),
            preserve_default=False,
        ),
    ]
