# Generated by Django 6.0.5 on 2026-07-11 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0015_progressimage_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressimage',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_image', to='commissions.commission'),
        ),
    ]
