# Generated by Django 6.0.5 on 2026-07-17 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0016_alter_progressimage_commission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalImage',
        ),
    ]
